---
version: 0
os: linux
files:
  - Source: /index.html
    destination: /var/www/html/
hooks:
  Before Install:
    - location: scripts/install dependencies
      timeout: 300
      runas: root
    - location: scripts/start_server
      timeout: 300
      runas: root
